baseURL = 'https://zakforster.com/'
languageCode = 'en-gb'
title = 'Zak Forster'
theme = 'blowfish'

[params.author]
name = "Zak Forster"
image = "img/zak.jpg"
headline = "Test"
bio = "A little bit about me"

[caches]
  [caches.images]
    dir = ':cacheDir/images'